services:
  - type: web
    name: virelia-tracker-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://vireliaUser:9847546823Divy%40@cluster0.eok5zus.mongodb.net/virelia-tracker?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: The mind is everything. What you think, you become. â€” Gautam Buddha
      - key: CLIENT_URL
        value: https://virelia-tracker-frontend-apztn9poi-kabiraj-1s-projects.vercel.app
      - key: NODE_ENV
        value: production
